# Site Settings
title: "My AI Notes"
author: Shyaam Prasadh
description: "Documenting my learning and insights on AI, Deep Learning, and AI Alignment."
baseurl: "/myAInotes"  # Adjust based on your repository name
url: "https://sprasadhpy.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
